o Don't print Unicode chars in LaTeX output o Allow scripts to use wvWare in path o Move version number to configure.in
git-svn-id: svn+ssh://svn.abisource.com/svnroot/wv/trunk@20511 bcba8976-2d24-0410-9c9c-aab3bd5fdfd6

diff --git a/wvAbw.in b/wvAbw.in
--- a/wvAbw.in
+++ b/wvAbw.in
@@ -100,8 +100,13 @@ wv_exec="$exec_prefix/bin/wvWare"
 if test -x "$wv_exec"; then
   okay=yes
 else
-  echo "error: no executable at '$wv_exec'"
-  exit 1
+  wv_version=`wvWare -v 2>&1 | cut -f 2 -d " "`
+  if test "x$wv_version" = "x@VERSION@"; then
+    wv_exec="wvWare"
+  else
+    echo "error: no executable at '$wv_exec' or in path"
+    exit 1
+  fi
 fi
 
 if test "x$datadir" = "x"; then
