o more script updates; support for ImageMagick's convert in wvDVI & wvPS o support for automatic conversion of PNG & JPEG to EPS via (latest) libwmf o new command-line options (--auto-eps & --suppress) for wvWare
git-svn-id: svn+ssh://svn.abisource.com/svnroot/wv/trunk@20513 bcba8976-2d24-0410-9c9c-aab3bd5fdfd6

diff --git a/wvPS.in b/wvPS.in
--- a/wvPS.in
+++ b/wvPS.in
@@ -6,6 +6,12 @@ if [ ${?} -ne "0" ]; then
   exit 1
 fi
 
+which dvips >/dev/null 2>&1
+if [ ${?} -ne "0" ]; then
+  echo "Could not find required program 'dvips'"
+  exit 1
+fi
+
 prefix=@prefix@
 exec_prefix=
 datadir=
@@ -259,5 +265,11 @@ if [ ! -f "$name".dvi ]; then
 	exit 1
 fi
 
-cp -f "$name".dvi "$o_file"
+dvips -o "$o_file" "$name".dvi >/dev/null 2>&1
+if [ ${?} -ne "0" ]; then
+	echo "Could not convert into Postscript"
+	exit 1
+fi
+
+#clean up
 rm -f "$name".dvi
