patch to wvHtml and wvText
git-svn-id: svn+ssh://svn.abisource.com/svnroot/wv/trunk@20858 bcba8976-2d24-0410-9c9c-aab3bd5fdfd6

diff --git a/wvText.in b/wvText.in
--- a/wvText.in
+++ b/wvText.in
@@ -3,7 +3,7 @@
 prefix=@prefix@
 exec_prefix=@exec_prefix@
 datadir=@datadir@
-tmpdir=/tmp
+tmpdir=${TMPDIR:-/tmp}
 
 # argument checking
 if [ ${#} -ne "2" ]; then
@@ -11,16 +11,20 @@ if [ ${#} -ne "2" ]; then
 	exit 1
 fi
 
-# start out optimistic
-USING_LYNX=1
-which lynx >/dev/null 2>&1
-if [ ${?} -ne "0" ]; then
-	echo "Could not find required program 'lynx'"
-	echo "Not using lynx. Ouput will be pretty bad."
-	USING_LYNX=0
+USE_DUMP=0
+which elinks >/dev/null 2>&1 && USE_DUMP=2 || { which lynx >/dev/null 2>&1 && USE_DUMP=1;}
+
+if [ $USE_DUMP -eq "1" ]; then
+	echo "Could not find required program 'elinks'"
+	echo "Using lynx. Ouput will be pretty ugly."
 fi
 
-if [ ${USING_LYNX} -ne "0" ]; then
+if [ $USE_DUMP -eq "0" ]; then
+	echo "Could not find required program 'elinks' or even 'lynx'"
+	echo "Using wvWare -x wvText.xml. Ouput will be pretty bad."
+fi
+
+if [ $USE_DUMP -gt "0" ]; then
 
     # first, test for wvHtml
     which wvHtml >/dev/null 2>&1
@@ -30,18 +34,26 @@ if [ ${USING_LYNX} -ne "0" ]; then
     fi
 
     # intermediate file
-    TMP_FILE="wv$$.html"
+    TMP_FILE=`mktemp "$tmpdir/wv-XXXXXX"`
+    TMP_FILE=`basename "$TMP_FILE"`
 
-    wvHtml "${1}" --targetdir="${tmpdir}" "${TMP_FILE}" >/dev/null 2>&1
+    wvHtml -1 "${1}" --targetdir="${tmpdir}" "${TMP_FILE}" >/dev/null 2>&1
     if [ ${?} -ne "0" ]; then
 	echo "Could not convert into HTML"
 	exit 1
     fi
 
-    # lynx actually does quite well
-    TERM=vt100 lynx -dump -force_html "${tmpdir}/${TMP_FILE}" > "${2}"
+    if [ $USE_DUMP -eq "2" ]; then
+	# elinks does the best
+	elinks -dump -force-html "${tmpdir}/${TMP_FILE}" > "${2}"
+    else
+	# lynx actually does quite well
+	TERM=vt100 lynx -dump -force_html "${tmpdir}/${TMP_FILE}" > "${2}"
+    fi;
+
     if [ ${?} -ne "0" ]; then
 	    echo "Could not convert into Text"
+	    rm -f "${tmpdir}/${TMP_FILE}"
 	    exit 1
     fi
 
